MyBlog/Models/ErrorViewModel.cs
namespace MyBlog.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MyBlog/Models/MyAlbumDetailViewModel.cs
using Models;

namespace MyBlog.Models;

public class MyAlbumDetailViewModel
{
    public Album Album { get; set; }
    public List<Photo> Photos { get; set; }
}

MyBlog/Models/MyPostDetailViewModel.cs
using System.Collections;
using Models;

namespace MyBlog.Models;

public class MyPostDetailViewModel
{
    public Post Post { get; set; }
    public List<Comment> Comments { get; set; }
}

MyBlog/Controllers/AccountController.cs
using System.Security.Claims;
using BLL.Interfaces;
using Core;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace MyBlog.Controllers;

public class AccountController : Controller
{
    private readonly ILoginService _loginService;
    public AccountController(ILoginService loginService)
    {
        _loginService = loginService;
    }

    public IActionResult Login()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Login(string name, string password, string returnUrl)
    {
        if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(password))
        {
            return RedirectToAction("Login");
        }

        var user = _loginService.login(name, password);

        if (user == null)
        {
            return RedirectToAction("Login");
        }

        var identity = new ClaimsIdentity(new[]
        {
            new Claim(ClaimTypes.Name, name),
            new Claim(ClaimTypes.Role, "User")
        }, CookieAuthenticationDefaults.AuthenticationScheme);

        var principal = new ClaimsPrincipal(identity);
        var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

        if (Utils.IsLocalUrl(returnUrl))
        {
            return Redirect(returnUrl);
        }
        
        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public IActionResult Logout()
    {
        var login = HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("Login");
    }
}

MyBlog/Controllers/HomeController.cs
using System.Diagnostics;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Models;
using MyBlog.Models;

namespace MyBlog.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger, ILoginService loginService)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        // var user = _loginService.login("Shanna@melissa.tv", "");
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
    }
}

MyBlog/Controllers/MyPageController.cs
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Common;
using MyBlog.Models;

namespace MyBlog.Controllers;


public class MyPageController : UserControllerBase
{
    private readonly IPostService _postService;
    private readonly IAlbumService _albumService;
    private readonly ICommentService _commentService;
    private readonly IPhotoService _photoService;
    
    public MyPageController(IPostService postService, IAlbumService albumService, ICommentService commentService, IPhotoService photoService)
    {
        _postService = postService;
        _albumService = albumService;
        _commentService = commentService;
        _photoService = photoService;
    }
    
    
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult MyPost()
    {
        return View(_postService.GetPosts());
    }

    [HttpGet("/MyPage/MyPost/{id}")]
    public IActionResult MyPostDetail(int id)
    {
        var viewModel = new MyPostDetailViewModel();

        var post = _postService.GetPosts().Find(post => post.Id == id);

        if (post != null)
        {
            var comments = _commentService.GetCommentsByPostId(id);
            viewModel.Post = post;
            viewModel.Comments = comments;
        }

        return View(viewModel);
    }

    public IActionResult MyAlbum()
    {
        return View(_albumService.GetAlbums());
    }

    [HttpGet("/MyPage/MyAlbum/{id}")]
    public IActionResult MyPhotos(int id)
    {
        var viewModel = new MyAlbumDetailViewModel();

        var album = _albumService.GetAlbums().Find(album => album.Id == id);

        if (album != null)
        {
            viewModel.Album = album;
            viewModel.Photos = _photoService.GetPhotosByAlbumId(id);
        }
        return View(viewModel);
    }
}

MyBlog/Pages/User/Login.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

MyBlog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Coredsdsdsdfsdf</a>.</p>
</div>

MyBlog/Views/MyPage/Index.cshtml
<div class="row">
    <div class="col-md-5">
        @Html.ActionLink("내 포스팅", "MyPost", "MyPage")
    </div>
</div>

<div class="row">
    <div class="col-md-5">
        @Html.ActionLink("내 앨범", "MyAlbum", "MyPage")
    </div>
</div>

MyBlog/Views/MyPage/MyAlbum.cshtml
@model List<Models.Album>

    
@foreach (var item in Model)
{
        <div class="row">
                <div class="col-md-5">
                        <a class="nav-link text-blue" asp-area="" asp-controller="MyPage" asp-action="MyPhotos" asp-route-id="@item.Id">
                                @item.Title        
                        </a>
                </div>
        </div>
}
        

MyBlog/Views/MyPage/MyPhotos.cshtml
@model MyAlbumDetailViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>앨범 상세</h2>

<div class="row">
    <div class="col-md-3">@Model.Album.UserId</div>
</div>
<div class="row">
    <div class="col-md-3">@Model.Album.Title</div>
</div>


<h3>목록</h3>
@foreach (var item in Model.Photos)
    {
        <div class="row">
            <div class="col-md-2">
                <img src="@item.ThumbnailUrl" alt="@item.Title"/>
            </div>
            <div class="col-md-5">
                <p>@item.Title</p>
            </div>
        </div>
    }        

MyBlog/Views/MyPage/MyPost.cshtml
@model List<Models.Post>


    
@foreach (var item in Model)
{
<div class="row">
        <div class="col-md-5">
                <a class="nav-link text-blue" asp-area="" asp-controller="MyPage" asp-action="MyPostDetail" asp-route-id="@item.Id">
                        @item.Title        
                </a>
        </div>
</div>
}

MyBlog/Views/MyPage/MyPostDetail.cshtml
@model MyPostDetailViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>포스트 상세</h2>

<div class="row">
    <div class="col-md-3">@Model.Post.UserId</div>
</div>
<div class="row">
    <div class="col-md-3">@Model.Post.Title</div>
</div>
<div class="row">
    <div class="col-md-5">@Model.Post.Body</div>
</div>


<h3>댓글</h3>
@foreach (var item in Model.Comments)
    {
        <div class="row">
            <div class="col-md-3">@item.Id</div>
            <div class="col-md-3">@item.Body</div>
            <div class="col-md-3">@item.Email</div>
            <div class="col-md-3">@item.Name</div>
        </div>
    }
        

MyBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MyBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/MyBlog.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyBlog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="MyPage" asp-action="Index">MyPage</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - MyBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>